import Head from 'next/head'
import Layout from '../components/MyLayout';
import Image from 'next/image'
import myPhoto from "./myPhoto.jpeg"

// css in JSX format.
const landingDiv = {
  marginTop: 40,
};
const photo = {
  width: 200,
  marginTop: 20,
};

function Home() {
  return (
    <div>
      <Head>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-229683137-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)}
  gtag('js', new Date());

  gtag('config', 'UA-229683137-1');
</script>

        <title>TJ Jacobs | Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
    <div style={landingDiv}>
      <div>
        <h2>TJ Jacobs</h2>
        <h4>Web developer / Fishing guide</h4>
      </div>
      <div>
        {/* here I use a static image */}
        <Image style={photo} alt='imagenew' width="200px"
      height="250px" src={myPhoto}/>
      </div>
    </div>
  </Layout>
    </div>
  )
}

export default Home;
